analytics: {}
color:
  brandColors:
    - '#E0D8C8'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#F8F8D8'
  brandStrength: 0.649774
  lightness: 0.105088
  rhythmicContrast: 0.36036
  saturation: 0.389095
cta: {}
layout_spectrum: 0
name: plattitude
opengraph: {}
purpose: []
typography_spectrum: 0.404279
