typography_spectrum: 0.404279
color:
  brandColors:
    - '#E0D8C8'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#F8F8D8'
  brandStrength: 0.649774
  lightness: 0.105088
  rhythmicContrast: 0.36036
  saturation: 0.389095
opengraph: {}
layout_spectrum: 0
analytics: {}
name: Plattitude
cta: {}
navigation:
  - name: Water
    id: 3e9ea8c5-8bc7-4a2a-a62d-21db4bf63272
    type: content
title: Head1
description: Tag1
purpose: []
